title: Colm Prunty
description: Writing about stuff

url: http://blog.colmprunty.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  twitter: colmprunty

google_analytics: "UA-155260331-1"
