title: Colm Prunty
description: Writing about stuff

url: http://blog.colmprunty.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Writing
    url: /writing
  - title: Books
    url: /books
  - title: Movies
    url: /movies

social:
  twitter: colmprunty
